server:
   Describe: 一台330屏的连接信息
   broker: test.hzjishiyu.com
   port: 1883
   keepalive: 60
DID330:
   client_id: DID330&300133121210002
   username: DID330&300133121210002
   password: DID330&300133121210002&3c9951a811d745fbbda6f2a0843ccf19
   productKey: DID330
   deviceName: 300133121210002
DID330_2:
   client_id: DID330&300133123050002
   username: DID330&300133123050002
   password: DID330&300133123050002&c07d359b30de4997a586f5489d7fce7a
   productKey: DID330
   deviceName: 300133123050002
   secret: c07d359b30de4997a586f5489d7fce7a
DID340:
   client_id: DID340&300134121210008
   username: DID340&300134121210008
   password: DID340&300134121210008&515af789c7a64817abf4aadff4ac9f12
   secret: 515af789c7a64817abf4aadff4ac9f12
   productKey: DID340
   deviceName: 300134121210008
JTC340:
   productKey: JTC340
   deviceName: 100334121210009
   Secret: d5e214693c9348228f50b977b61cf2e7
topic:
   get_property:
      sub: /device/{}/{}/thing/service/property/get_reply/
      pub: /server/{}/{}/thing/service/property/get/
   set_property:
      sub: /device/{}/{}/thing/service/property/set_reply/
      pub: /server/{}/{}/thing/service/property/set/
   post_property:
      sub: /server/{}/{}/thing/event/property/post_reply/
      pub: /device/{}/{}/thing/event/property/post/
   post_call:
      sub: /server/{}/{}/thing/event/Call/post_reply/
      pub: /device/{}/{}/thing/event/Call/post/
   GetWeather_post:
      sub: /server/{}/{}/thing/event/GetWeather/post_reply/
      pub: /device/{}/{}/thing/event/GetWeather/post/
   addnormaladvertlist:
      sub: /device/{}/{}/thing/service/addnormaladvertlist_replay/
      pub: /server/{}/{}/thing/service/addnormaladvertlist/
   deladvertlist:
      sub: /device/{}/{}/thing/service/deladvertlist_replay/
      pub: /server/{}/{}/thing/service/deladvertlist/
   log2aliyun:
      sub: /device/{}/{}/thing/service/log2aliyun_replay/
      pub: /server/{}/{}/thing/service/log2aliyun/
   startreportinfo:
      sub: /device/{}/{}/thing/service/startreportinfo_replay/
      pub: /server/{}/{}/thing/service/startreportinfo/
   PlayStatistics:
      sub: /server/{}/{}/thing/event/PlayStatistics/post_reply/
      pub: /device/{}/{}/thing/event/PlayStatistics/post/
   LiveData_post:
      sub: /server/{}/{}/thing/event/LiveData/post_reply/
      pub: /device/{}/{}/thing/event/LiveData/post/
   RunStatistics_post:
      sub: /server/{}/{}/thing/event/RunStatistics/post_reply/
      pub: /device/{}/{}/thing/event/RunStatistics/post/
   ntp_post:
      sub: /server/{}/{}/thing/event/ntp/post_reply/
      pub: /device/{}/{}/thing/event/ntp/post/
   post_property_JTC340:
      sub: /server/{}/{}/thing/event/property/post_reply/
      pub: /device/{}/{}/thing/event/property/post/
   service_upgrade:
      sub: /device/{}/{}/thing/service/upgrade_reply/
      pub: /server/{}/{}/thing/service/upgrade/
   service_upgrade_DID340:
      sub: /device/{}/{}/thing/service/upgrade_replay/
      pub: /server/{}/{}/thing/service/upgrade/
   ErrorEvent_post:
      sub: /server/{}/{}/thing/event/ErrorEvent/post_reply/
      pub: /device/{}/{}/thing/event/ErrorEvent/post/
   ErrorClose_post:
      sub: /server/{}/{}/thing/event/ErrorClose/post_reply/
      pub: /device/{}/{}/thing/event/ErrorClose/post/
   LockEvent_post:
      sub: /server/{}/{}/thing/event/LockEvent/post_reply/
      pub: /device/{}/{}/thing/event/LockEvent/post/
   LockClose_post:
      sub: /server/{}/{}/thing/event/LockClose/post_reply/
      pub: /device/{}/{}/thing/event/LockClose/post/
   SelfError_post:
      sub: /server/{}/{}/thing/event/SelfError/post_reply/
      pub: /device/{}/{}/thing/event/SelfError/post/
   AlarmEvent_post:
      sub: /server/{}/{}/thing/event/AlarmEvent/post_reply/
      pub: /device/{}/{}/thing/event/AlarmEvent/post/
   AlarmClose_post:
      sub: /server/{}/{}/thing/event/AlarmClose/post_reply/
      pub: /device/{}/{}/thing/event/AlarmClose/post/
   service_reboot:
      sub: /device/{}/{}/thing/service/reboot_reply/
      pub: /server/{}/{}/thing/service/reboot/
   service_reboot_DID340:
      sub: /device/{}/{}/thing/service/reboot_replay/
      pub: /server/{}/{}/thing/service/reboot/
   service_getlog:
      sub: /device/{}/{}/thing/service/getlog_reply/
      pub: /server/{}/{}/thing/service/getlog/
msg:
   get_property:
      -
         Version: 1.0
         Params:
            PropNames: ServerConfig
      -
         Version: 1.0
         Params:
            PropNames: DeviceInfo
      -
         Version: 1.0
         Params:
            PropNames: CurrentAdverts
      -
         Version: 1.0
         Params:
            PropNames: SleepConfig
      -
         Version: 1.0
         Params:
            PropNames: ElevatorConfig
      -
         Version: 1.0
         Params:
            PropNames: PhoneConfig
   set_property:
      -
         Version: 1.0
         Params:
            PhoneConfig:
               -
                  PhoneName: phone1
                  PhoneNo: 13000000000
               -
                  PhoneName: phone2
                  PhoneNo: 13011111111
            VoiceConfig:
               -
                  StartTime: "09_00"
                  EndTime: "11_35"
                  Voice: 10
               -
                  StartTime: "11_36"
                  EndTime: "23_59"
                  Voice: 30
            SleepConfig:
               -
                  StartTime: "19_00"
                  EndTime: "23_59"
               -
                  StartTime: "00_01"
                  EndTime: "08_59"
      -
         Version: 1.0
         Params:
            deviceWriteType: IS_NOTICE_CONFIG_340
            NoticeConfig:
               -
                  Content: 大傻子
                  Sign: "428"
   post_property:
      Version: 1.0
      Params:
         PhoneConfig:
            -
               PhoneName: phone1
               PhoneNo: 13000000000
            -
               PhoneName: phone2
               PhoneNo: 13011111111
         VoiceConfig:
            -
               StartTime: "09_00"
               EndTime: "11_35"
               Voice: 0
            -
               StartTime: "11_36"
               EndTime: "23_59"
               Voice: 10
         SleepConfig:
            -
               StartTime: "19_00"
               EndTime: "23_59"
            -
               StartTime: "00_01"
               EndTime: "08_59"
   post_call:
      Version: 1.0
      Params:
         Value:
           CallTime: "2023/08/09 10:00:00"
         Time: 1524448722000
   GetWeather_post:
      Version: 1.0
      Params:
         Time: 1524448722000
   LiveData_post:
      Version: 1.0
      Params:
         Value:
            DoorState: 1
            PersonState: 1
            CurrentFloor: -2B
            RunDirection: 1
            RunState: 1
   RunStatistics_post:
      Version: 1.0
      Params:
         Value:
            StartTime: "2021/4/14 00:00:00"
            EndTime: "2021/4/15 00:00:00"
            DoorToggleCount: 100
            RunMins: 100
            RunMileage: 100
            RunCount: 100
            RunMeters: 300
         Time: 1524448722000
   service_upgrade_DID340:
      Version: "1.0"
      Params:
         deviceWriteType: IS_UPGRADE_340
         Version: "301.34.23.0616"
         Hash: "490D782D8312BBB81639D60DBFCA28DF"
         Url: https://jsy-saas-cloud-test.oss-cn-hangzhou.aliyuncs.com/download-KRzvjmqTcggj_301.34.23.0616.apk
   addnormaladvertlist:
      Version: "1.0"
      Params:
         deviceWriteType: IS_ADD_NORMAL_ADVERT_LIST_340
         EndTime: 1695830399000
         Materials:
            -
               MaterialId: "1557523625756553409"
               Resources:
                  -
                     Type: 2
                     Duration: 15
                     Id: "4459248051672234862"
                     Hash: "7E417BF07E070512F0C22DBB30D97BDA"
                     Url: "https://jsy-saas-cloud-test.oss-cn-hangzhou.aliyuncs.com/JsySaasCloud/adPC/material/U9T913vFp49ED719660E4427589C420DA676DF7AC_1080x1764.mp4"
                     Resolution: "1080*1764"
         StartTime: 1695052800000
         Code: "8705030108139154481"
   log2aliyun:
      Version: "1.0"
      Params:
         deviceWriteType: IS_LOG2ALIYUN_340
         StartTime: "2023-09-19 10:00:00"
         Url: "https://jsy-saas-cloud-test.oss-cn-hangzhou.aliyuncs.com/?accessKeyId=STS.NTA7MbUoxUj3Cc1nNLPMrJXTP\u0026accessKeySecret=4eK1ZcR3fnEb7iMULhse3ksiW1rHijwuxocZk8b13DHr\u0026securityToken=CAIS/QJ1q6Ft5B2yfSjIr5f0fPfWuLBZ4qjYQUWAik4ZXMJepZ3/sjz2IHFJdHJtAe0ZsP4znmlQ6/gclqJoVpV/QkjJS8J148zlG9wSodOT1fau5Jko1bcecAr6Umxeta2/SuH9S8ynNZXJQlvYlyh17KLnfDG5JTKMOoGIjpgVCbZyWRKjPwJbGPBcJAZptLXoXBm3D/u2NQPwiWf9FVdhvhEG6Vly8qOi2MaRmAy82FTx0b0SvJ\u002BjYMrmPct3LdJkWt6umedycbfNlTJd8AQN1rxnt6VN4hzDucyRRF5J\u002BC2NdObZ7NxkISt\u002BacpsEqVf/v/njq866K6BlZ/mjg1ENPoQWCDYWYzl3MbfBKSLLccCfL/gEHDKz9zIMYHuiwhjbX8FNQhHX90ubT1ScUVyE2uBcvb5pwiTMlb4FPW/vftogcYv/TLB5sGXIlWDebKd3BsDN4U0B0FSbE9LjTe8KvJZLVYQKQo/WujLV\u002BRydwxZsrjsugLCgdfCRIrzOZcagAGTa7iVG/ksZe24GOMc4\u002BCIZ1FZ03yGhqCc8JB80pE77bkPME4Ijwpg\u002BGJqfqRtImk8uKO2UME4LIkVikCBvtjq4xoUIL09nDeNr5aGPq9otK17u96oI0HPYM0Zcg4yxKziKg0qScO9ju0hnjon4FH/4d8m1Z8Y3acJUPvHwEs05yAA\u0026expiration=2023-09-19T03:13:31Z\u0026objectKey=JsySaasCloud/opsPc/deviceLog/\u0026fileName=DID340-300134121210008-1695089610862.log"
   deladvertlist:
      Version: "1.0"
      Params:
         deviceWriteType: IS_DEL_ADVERT_LIST_340
         Codes:
            -
               "7543616665691446726"
   startreportinfo:
      Version: "1.0"
      Params:
         deviceWriteType: IS_START_REPORT_INFO_340
         Time: 600
   PlayStatistics:
      Version: "1.0"
      Params:
         Value:
            Lists:
               -
                  Code: "8705030108139154481"
                  Times: 235
            Resources:
               -
                  Code: "8705030108139154481"
                  Duration: 3544
                  MaterialId: "1557523625756553409"
                  Times: 235
         Time: 1695115373901
   ntp_post:
      Version: 1.0
      DSTime: 1571724098000
   get_property_JTC340:
      -
         Version: 1.0
         Params:
            PropNames: DeviceInfo
      -
         Version: 1.0
         Params:
            PropNames: ServerConfig
      -
         Version: 1.0
         Params:
            PropNames: ErrorConfig
      -
         Version: 1.0
         Params:
            PropNames: FloorConfig
      -
         Version: 1.0
         Params:
            PropNames: PowerState
      -
         Version: 1.0
         Params:
            PropNames: SelfCheckConfig
      -
         Version: 1.0
         Params:
            PropNames: OtherConfig
   service_upgrade:
      Version: "1.0"
      Params:
         deviceWriteType: ECT_UPGRADE_340
         Version: 103.34.23.0616
         Hash: 7A06CC0BA104B3E11687E2DD2FE0D882
         Url: https://jsy-saas-cloud-test.oss-cn-hangzhou.aliyuncs.com/download-5K80jGXRLrtthread.rbl
   set_property_JTC340:
      -
        Version: "1.0"
        Params:
           deviceWriteType: ECT_UPGRADE_340
           ErrorConfig:
              BlockDoor: 45
              DoorRepeat: 4
              StayTrapped: 1
              StatusManage: 0
              OutSideTrapped: 1
              DoorError: 5
              StatyLockTimeOut: 180
              LockTimeOut: 30
      -
         Version: "1.0"
         Params:
            deviceWriteType: ECT_UPGRADE_340
            FloorConfig:
               FloorTable: "-1,1,2,3,4,5"
               BaseFloor: "1"
               Nfloors: "-1"
               SkipFloors: ""
               MaxFloor: 5
               FloorHeight: 300
      -
        Version: "1.0"
        Params:
           deviceWriteType: ECT_UPGRADE_340
           ServerConfig:
              ServerAddress: test.hzjishiyu.com
              ServerPort: 1883
              KeepAlive: 20
              CleanSession: 0
              Secret: d5e214693c9348228f50b977b61cf2e7
      -
        Version: "1.0"
        Params:
           deviceWriteType: ECT_UPGRADE_340
           SelfCheckConfig:
              ErrorNum: 24
      -
        Version: "1.0"
        Params:
           deviceWriteType: ECT_UPGRADE_340
           OtherConfig:
              RunReportTime: 1
              IsRepair: 0
   post_property_JTC340:
      -
         Version: "1.0"
         Params:
            ErrorConfig:
               BlockDoor: 45
               DoorRepeat: 4
               StayTrapped: 1
               StatusManage: 0
               OutSideTrapped: 1
               DoorError: 5
               StatyLockTimeOut: 180
               LockTimeOut: 30
      -
         Version: "1.0"
         Params:
            FloorConfig:
               FloorTable: "-1,1,2,3,4,5"
               BaseFloor: "1"
               Nfloors: "-1"
               SkipFloors: ""
               MaxFloor: 5
               FloorHeight: 300
      -
        Version: "1.0"
        Params:
           ServerConfig:
              ServerAddress: test.hzjishiyu.com
              ServerPort: 1883
              KeepAlive: 10
              CleanSession: 0
              Secret: d5e214693c9348228f50b977b61cf2e7
      -
        Version: "1.0"
        Params:
           SelfCheckConfig:
              ErrorNum: 24
      -
        Version: "1.0"
        Params:
           PowerState:
              -
                 Module: 1
                 Toggle: 1
              -
                 Module: 2
                 Toggle: 1
              -
                 Module: 3
                 Toggle: 1
      -
        Version: "1.0"
        Params:
           OtherConfig:
              RunReportTime: 1
              IsRepair: 0
      -
        Version: "1.0"
        Params:
           StaticIp:
              IP: "192.168.0.28"
   ErrorEvent_post:
      -
         Version: "1.0"
         Params:
            Value:
               ErrorType: 1001
               ErrorTime: "2023-08-16 16:25:07"
            Time: 1692167107
      -
         Version: "1.0"
         Params:
            Value:
               ErrorType: 1002
               ErrorTime: "2023-08-16 16:26:07"
            Time: 1692167107
      -
         Version: "1.0"
         Params:
            Value:
               ErrorType: 1003
               ErrorTime: "2023-08-16 16:27:07"
            Time: 1692167107
      -
         Version: "1.0"
         Params:
            Value:
               ErrorType: 1004
               ErrorTime: "2023-08-16 16:28:07"
            Time: 1692167107
      -
         Version: "1.0"
         Params:
            Value:
               ErrorType: 1005
               ErrorTime: "2023-08-16 16:29:07"
            Time: 1692167107
      -
         Version: "1.0"
         Params:
            Value:
               ErrorType: 1006
               ErrorTime: "2023-08-16 16:30:07"
            Time: 1692167107
      -
         Version: "1.0"
         Params:
            Value:
               ErrorType: 1007
               ErrorTime: "2023-08-16 16:31:07"
            Time: 1692167107
      -
         Version: "1.0"
         Params:
            Value:
               ErrorType: 1008
               ErrorTime: "2023-08-16 16:32:07"
            Time: 1692167107
      -
         Version: "1.0"
         Params:
            Value:
               ErrorType: 1009
               ErrorTime: "2023-08-16 16:33:07"
            Time: 1692167107
   ErrorClose_post:
      -
         Version: "1.0"
         Params:
            Value:
               ErrorType: 1001
               CloseTime: "2023-08-16 16:28:07"
            Time: 1692167117
      -
         Version: "1.0"
         Params:
            Value:
               ErrorType: 1002
               CloseTime: "2023-08-16 16:29:07"
            Time: 1692167117
      -
         Version: "1.0"
         Params:
            Value:
               ErrorType: 1003
               CloseTime: "2023-08-16 16:30:07"
            Time: 1692167117
      -
         Version: "1.0"
         Params:
            Value:
               ErrorType: 1004
               CloseTime: "2023-08-16 16:31:07"
            Time: 1692167117
      -
         Version: "1.0"
         Params:
            Value:
               ErrorType: 1005
               CloseTime: "2023-08-16 16:32:07"
            Time: 1692167117
      -
         Version: "1.0"
         Params:
            Value:
               ErrorType: 1006
               CloseTime: "2023-08-16 16:33:07"
            Time: 1692167117
      -
         Version: "1.0"
         Params:
            Value:
               ErrorType: 1007
               CloseTime: "2023-08-16 16:34:07"
            Time: 1692167117
      -
         Version: "1.0"
         Params:
            Value:
               ErrorType: 1008
               CloseTime: "2023-08-16 16:35:07"
            Time: 1692167117
      -
         Version: "1.0"
         Params:
            Value:
               ErrorType: 1009
               CloseTime: "2023-08-16 16:36:07"
            Time: 1692167117
   LockEvent_post:
      -
         Version: "1.0"
         Params:
            Value:
               Type: 1
               LockTime: "2023-08-16 16:28:07"
            Time: 1692167117
      -
         Version: "1.0"
         Params:
            Value:
               Type: 2
               LockTime: "2023-08-16 16:28:07"
            Time: 1692167117
      -
         Version: "1.0"
         Params:
            Value:
               Type: 0
               LockTime: "2023-08-16 16:28:07"
            Time: 1692167117
   LockClose_post:
      -
         Version: "1.0"
         Params:
            Value:
               Type: 1
               CloseTime: "2023-08-16 16:28:07"
            Time: 1692167117
      -
         Version: "1.0"
         Params:
            Value:
               Type: 2
               CloseTime: "2023-08-16 16:28:07"
            Time: 1692167117
      -
         Version: "1.0"
         Params:
            Value:
               Type: 0
               CloseTime: "2023-08-16 16:28:07"
            Time: 1692167117
   SelfError_post:
      -
         Version: "1.0"
         Params:
            Value:
               ErrorType: 3001
               OccurTime: "2023-08-16 16:28:07"
            Time: 1692167117
      -
         Version: "1.0"
         Params:
            Value:
               ErrorType: 3002
               OccurTime: "2023-08-16 16:28:07"
            Time: 1692167117
      -
         Version: "1.0"
         Params:
            Value:
               ErrorType: 3003
               OccurTime: "2023-08-16 16:28:07"
            Time: 1692167117
      -
         Version: "1.0"
         Params:
            Value:
               ErrorType: 3004
               OccurTime: "2023-08-16 16:28:07"
            Time: 1692167117
   AlarmEvent_post:
      -
         Version: "1.0"
         Params:
            Value:
               AlarmType: 2002
               AlarmTime: "2023-08-16 16:28:07"
            Time: 1692167117
      -
         Version: "1.0"
         Params:
            Value:
               AlarmType: 2003
               AlarmTime: "2023-08-16 16:28:07"
            Time: 1692167117
   AlarmClose_post:
      -
         Version: "1.0"
         Params:
            Value:
               AlarmType: 2002
               CloseTime: "2023-08-16 16:28:07"
            Time: 1692167117
      -
         Version: "1.0"
         Params:
            Value:
               AlarmType: 2003
               CloseTime: "2023-08-16 16:28:07"
            Time: 1692167117
   service_reboot:
      Version: "1.0"
      Params:
   service_getlog:
      Version: "1.0"
      Params:
         deviceWriteType: ECT_GET_LOG_340
         FileUploadServerUrl: http://test-ops.21.hzjishiyu.com/jsy-api-ops-pc/ops/pc/file/ectlog_upload
         SaasId: "1"